
trigger:
- main
- feature

variables: 
- group: Retention
pool:
  vmImage: windows-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
